/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SvgSample {}
  interface SvgSampleAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SvgSample': Components.SvgSample;
  }

  interface StencilIntrinsicElements {
    'svg-sample': Components.SvgSampleAttributes;
  }


  interface HTMLSvgSampleElement extends Components.SvgSample, HTMLStencilElement {}
  var HTMLSvgSampleElement: {
    prototype: HTMLSvgSampleElement;
    new (): HTMLSvgSampleElement;
  };

  interface HTMLElementTagNameMap {
    'svg-sample': HTMLSvgSampleElement
  }

  interface ElementTagNameMap {
    'svg-sample': HTMLSvgSampleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
